### ISSUE TITLE
Sandboxable.Microsoft.WindowsAzure.Storage not signed

### ISSUE THREAD

**Issue by sbosman84** [Winvision/Sandboxable#2]
We are using the 'Sandboxable.Microsoft.WindowsAzure.Storage' dll in a signed project and received the following error:

Referenced assembly 'Sandboxable.Microsoft.WindowsAzure.Storage, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Could there be a signed version of this library? :-)

**Comment by eNeRGy164** [comment]
Solved in 93eefa79
