### ISSUE TITLE
Sandboxable Nuget Packages no longer available via nuget restore

### ISSUE THREAD

**Issue by martintoelk** [Winvision/Sandboxable#5]
Hi eNeRGy164,

Thanks for developing a solution which also works in sandbox mode. We have currently the following Problem.
When I try to complie the Solution, I Encounter different missing Nuget Packges.

For Example:

Package 'Sandboxable.Hyak.Common.1.0.42' is not found on source 'https://api.nuget.org/v3/index.json'.
Package 'Sandboxable.Microsoft.Azure.Common.1.0.43' is not found on source 'https://api.nuget.org/v3/index.json'.

It seems, that the spefic Version is no longer available on nuget.

Best regards,

Martin

**Comment by eNeRGy164** [comment]
Sorry for the missing versions. These versions referenced were never publically available.
Try using the 1.1.0 versions of both packages.

Next time I update the packages I'll make sure the dependencies will be corrected.

**Comment by martintoelk** [comment]
Thanks it is compiling now! We will try it out and give you a Feedback. Thanks again and have a great Weekend :)
