### ISSUE TITLE
System.TypeInitializationException was unhandled

### ISSUE THREAD

**Issue by martintoelk** [Winvision/Sandboxable#6]
Hi Michaël,

we are currently trying to use the sandboxable dll from nuget. 

We are using the following Code:

 private static async Task<string> AuthenticationCallback(string authority, string resource, string scope)
        {
            return await Task.Factory.StartNew(() => $"{authority},{resource},{scope}");
        }
        static void Main(string[] args)
        {
            var ThisLineThrowsError= new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(new KeyVaultClient.AuthenticationCallback(AuthenticationCallback)));
            Console.ReadLine();
        }
Setting up the KeyVaultClient will result with the error message below:

System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for  "Sandboxable.Hyak.Common.ServiceClient`1" threw an exception.
  Source=Sandboxable.Hyak.Common
  TypeName=Sandboxable.Hyak.Common.ServiceClient`1
  StackTrace:
       bei Sandboxable.Hyak.Common.ServiceClient`1..ctor() in C:\projects\sandboxable\src\Hyak.Common\ServiceClient.cs:Zeile 76.
       bei Sandboxable.Microsoft.Azure.KeyVault.Internal.KeyVaultInternalClient..ctor() in C:\projects\sandboxable\src\Microsoft.Azure.KeyVault\Generated\KeyVaultInternalClient.cs:Zeile 109.
       bei Sandboxable.Microsoft.Azure.KeyVault.Internal.KeyVaultInternalClient..ctor(KeyVaultCredential credentials) in C:\projects\sandboxable\src\Microsoft.Azure.KeyVault\Generated\KeyVaultInternalClient.cs:Zeile 153.
       bei Sandboxable.Microsoft.Azure.KeyVault.KeyVaultClient..ctor(AuthenticationCallback authenticationCallback) in C:\projects\sandboxable\src\Microsoft.Azure.KeyVault\KeyVaultClient.cs:Zeile 58.
       bei ConsoleApplication3.Program.Main(String[] args) in C:\Users\mato0104\Documents\Visual Studio 2015\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:Zeile 18.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233079
       Message=Sequence contains no elements
       Source=System.Core
       StackTrace:
            bei System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
            bei Sandboxable.Hyak.Common.Internals.PortablePlatformAbstraction.GetPlatformTypeFullName[T](Assembly platformAssembly) in C:\projects\sandboxable\src\Hyak.Common\Internals\PortablePlatformAbstraction.cs:Zeile 112.
            bei Sandboxable.Hyak.Common.Internals.PortablePlatformAbstraction.Get[T](Boolean hasDefaultImplementation) in C:\projects\sandboxable\src\Hyak.Common\Internals\PortablePlatformAbstraction.cs:Zeile 51.
            bei Sandboxable.Hyak.Common.ServiceClient`1..cctor() in C:\projects\sandboxable\src\Hyak.Common\ServiceClient.cs:Zeile 70.
       InnerException: 

Best regards,

Martin

**Comment by eNeRGy164** [comment]
Hi, thanks for reporting the issue.

Fixed this with commit c8736ca1acb01ac7497ebb5a7d9c220f4f79a5a6
There was no implementation of the IHttpTransportHandlerProvider interface.
